import { Annotation } from "@langchain/langgraph";
import { ExecutionPlan, ArchitectureProfile } from "./schema";

export type { ExecutionPlan, ArchitectureProfile } from "./schema";

/**
 * Defines the structure of a generated file.
 */
export interface GeneratedFile {
  filePath: string;
  fileContent: string;
}

/**
 * The main state object for the LangGraph agent workflow.
 * This acts as the shared memory between agents.
 */
export const AgentState = Annotation.Root({
  /**
   * The title of the Jira ticket.
   */
  ticketSummary: Annotation<string>,

  /**
   * The detailed description from the Jira ticket.
   */
  ticketDescription: Annotation<string>,

  /**
   * A text representation of the project's current file structure.
   */
  codebaseTree: Annotation<string>,

  /**
   * The plan drafted by the Product Manager agent.
   */
  executionPlan: Annotation<ExecutionPlan>,

  /**
   * The code generated by the Frontend Engineer agent.
   */
  generatedCode: Annotation<GeneratedFile[]>,

  /**
   * The project configuration context (Next.js version, Tailwind, etc.).
   */
  projectContext: Annotation<string>,

  /**
   * The structured Architecture Profile generated by the Architecture Agent.
   */
  architectureProfile: Annotation<ArchitectureProfile>,

  /**
   * Whether the generated code needs revision.
   */
  needsRevision: Annotation<boolean>,

  /**
   * The validation errors found during the review.
   */
  validationErrors: Annotation<string[]>,
});
