import { Annotation } from "@langchain/langgraph";
import {
  ExecutionPlan,
  ArchitectureProfile,
  DesignSpecifications,
  TicketClassification,
} from "./schema";

export type {
  ExecutionPlan,
  ArchitectureProfile,
  DesignSpecifications,
  TicketClassification,
} from "./schema";

/**
 * Defines the structure of a generated file.
 */
export interface GeneratedFile {
  filePath: string;
  fileContent: string;
}

export interface Metrics {
  startTime: number;
  endTime?: number;
  totalDuration?: number;
  nodeExecutionTimes: Record<string, number>;
  nodeTokenUsage: Record<
    string,
    { prompt: number; completion: number; total: number }
  >;
  totalFilesGenerated: number;
  totalFilesModified: number;
  validationRetries: number;
}

/**
 * The main state object for the LangGraph agent workflow.
 * This acts as the shared memory between agents.
 */
export const AgentState = Annotation.Root({
  /**
   * The ID of the Jira ticket (e.g., PROJ-123).
   */
  ticketId: Annotation<string>,

  /**
   * The title of the Jira ticket.
   */
  ticketSummary: Annotation<string>,

  /**
   * The detailed description from the Jira ticket.
   */
  ticketDescription: Annotation<string>,

  /**
   * A text representation of the project's current file structure.
   */
  codebaseTree: Annotation<string>,

  /**
   * The plan drafted by the Product Manager agent.
   */
  executionPlan: Annotation<ExecutionPlan>,

  /**
   * The code generated by the Frontend Engineer agent.
   */
  generatedCode: Annotation<GeneratedFile[]>,

  /**
   * The project configuration context (Next.js version, Tailwind, etc.).
   */
  projectContext: Annotation<string>,

  /**
   * The structured Architecture Profile generated by the Architecture Agent.
   */
  architectureProfile: Annotation<ArchitectureProfile>,

  /**
   * The structured Design Specifications generated by the Design Agent.
   */
  designSpecifications: Annotation<DesignSpecifications>(),

  /**
   * The classification of the ticket (complexity, type).
   */
  ticketClassification: Annotation<TicketClassification>(),

  /**
   * Whether the generated code needs revision.
   */
  needsRevision: Annotation<boolean>,

  /**
   * The validation errors found during the review.
   */
  validationErrors: Annotation<string[]>,

  /**
   * The number of validation attempts made so far.
   */
  validationAttempts: Annotation<number>,

  /**
   * Performance and usage metrics.
   */
  metrics: Annotation<Metrics>({
    reducer: (current, update) => {
      // If update is null/undefined, keep current
      if (!update)
        return (
          current || {
            startTime: Date.now(),
            nodeExecutionTimes: {},
            nodeTokenUsage: {},
            totalFilesGenerated: 0,
            totalFilesModified: 0,
            validationRetries: 0,
          }
        );

      return {
        ...current,
        ...update,
        nodeExecutionTimes: {
          ...(current?.nodeExecutionTimes || {}),
          ...(update.nodeExecutionTimes || {}),
        },
        nodeTokenUsage: {
          ...(current?.nodeTokenUsage || {}),
          ...(update.nodeTokenUsage || {}),
        },
      };
    },
    default: () => ({
      startTime: Date.now(),
      nodeExecutionTimes: {},
      nodeTokenUsage: {},
      totalFilesGenerated: 0,
      totalFilesModified: 0,
      validationRetries: 0,
    }),
  }),
});
